/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int TIPO = 9;
  /** RegularExpression Id. */
  int OP = 10;
  /** RegularExpression Id. */
  int NEWVAR = 11;
  /** RegularExpression Id. */
  int PV = 12;
  /** RegularExpression Id. */
  int VIRG = 13;
  /** RegularExpression Id. */
  int APARA = 14;
  /** RegularExpression Id. */
  int FPARA = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int SOUT = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int REPEAT = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int THEN = 21;
  /** RegularExpression Id. */
  int UNTIL = 22;
  /** RegularExpression Id. */
  int ATTR = 23;
  /** RegularExpression Id. */
  int FUNC = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int TOKEN_ID = 27;
  /** RegularExpression Id. */
  int TOKEN_NUM = 28;
  /** RegularExpression Id. */
  int DIGITO = 29;
  /** RegularExpression Id. */
  int LETRA = 30;
  /** RegularExpression Id. */
  int DIGITOS = 31;
  /** RegularExpression Id. */
  int FRACAO = 32;
  /** RegularExpression Id. */
  int EXPO = 33;
  /** RegularExpression Id. */
  int LETDIGI = 34;
  /** RegularExpression Id. */
  int UNDSCO = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "<TIPO>",
    "<OP>",
    "\"newVar\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"System.output\"",
    "\"return\"",
    "\"repeat\"",
    "\"while\"",
    "\"then\"",
    "\"until\"",
    "\"=\"",
    "\"func\"",
    "\"true\"",
    "\"false\"",
    "<TOKEN_ID>",
    "<TOKEN_NUM>",
    "<DIGITO>",
    "<LETRA>",
    "<DIGITOS>",
    "<FRACAO>",
    "<EXPO>",
    "<LETDIGI>",
    "<UNDSCO>",
  };

}
